Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  CountComments: false
  Max: 250

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 7

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/PredicateName:
  NamePrefix:
    - is_

Metrics/AbcSize:
  Max: 45

Metrics/PerceivedComplexity:
  Max: 10

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - spec/support/blueprints.rb
    - test/blueprints.rb
    - Gemfile
    - bin/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - db/data/*
    - tmp/**/*
    - vendor/**/*
    - gems/**/*
    - "**/node_modules/**/*"

Style/ExtraSpacing:
  AllowForAlignment: true
