# https://github.com/mjacobus/test_runner/
#
# gem install test_runner
# bundle exec run_test the/test/file
# bundle exec run_test the/test/file --line=10
# bundle exec run_test the/test/file --all

adapters:
  rspec:
    adapter: rspec
  client:
    adapter: custom
    file_pattern: "client/.*.test.js"
    command: "cd client && ./node_modules/.bin/jest"
    commands:
      all: "{command}"
      file: "{command} {file}"
      line: "{command} {file}" # no line test so far
  frontend:
    adapter: custom
    file_pattern: "frontend/.*test.js"
    command: "cd frontend && ./node_modules/.bin/gulp test"
    commands:
      all: '{command}'
      file: 'cd frontend && echo {file} | sed "s/frontend\///" | xargs -I {} ./node_modules/.bin/gulp test --file {}'
      line: 'cd frontend && echo {file} | sed "s/frontend\///" | xargs -I {} ./node_modules/.bin/gulp test --file {}'
