language: ruby
sudo: false
cache: bundler
dist: xenial

rvm:
  - 2.4.4

env:
  - DB=mysql DATABASE_URL="mysql2://root@127.0.0.1:3306/field_service_test"

script:
  - RAILS_ENV=test bundle exec rake travis_ci
  - yarn install
  - cd client && yarn install && yarn run test

services:
  - mysql
