language: ruby
sudo: false
cache: bundler

rvm:
  # - 2.2.2
  # - 2.3.0
  - 2.4.0

env:
  - DB=mysql      DATABASE_URL="mysql2://root@127.0.0.1:3306/field_service_test"
  # - DB=postgresql DATABASE_URL="postgres://postgres@localhost/field_service_test"
  # - DB=sqlite

before_script:
  - yarn install
  - cd client && yarn install

script:
  - RAILS_ENV=test bundle exec rake travis_ci
  - yarn run test

# https://docs.travis-ci.com/user/database-setup/#MySQL-5.7
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
