version: '3'
services:
  db:
    image: "mysql:5.7"
    volumes:
      - ./var/postgresql:/lib/postgresql/data
      - ./var/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
