# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e1b93a30c26cb2692c1e0c029dccd16e32c1fe95987642388822962691ab137b07bcd7d6828ed0e77ca1b05bf7429f752762a9315b14d5bd5203ef92d87ea5

test:
  secret_key_base: f3d05e50f75f61350b38d4858fff6672150f891c3dd52cdc206e6149156fb4b9005e8fbd63126dcac4b273c08edc7da6d4804b65ca754602fd7197961f68b456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
